// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlhAH1x2EmDT0RvK1Yql9Oq6XIzbzUkO8',
    appId: '1:507312397854:web:6f7d69430062bac00c580f',
    messagingSenderId: '507312397854',
    projectId: 'rec-mart',
    authDomain: 'rec-mart.firebaseapp.com',
    databaseURL: 'https://rec-mart-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rec-mart.appspot.com',
    measurementId: 'G-T3NKMGW8PS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC14QhlKMbZPAkbpRT7UE3zNXqLIEpZW3U',
    appId: '1:507312397854:android:2001ca843a363b400c580f',
    messagingSenderId: '507312397854',
    projectId: 'rec-mart',
    databaseURL: 'https://rec-mart-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rec-mart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD59W4KGWYnPbGP7w427HwhWmh0MTT41T0',
    appId: '1:507312397854:ios:0552116ffa5f1e7a0c580f',
    messagingSenderId: '507312397854',
    projectId: 'rec-mart',
    databaseURL: 'https://rec-mart-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rec-mart.appspot.com',
    androidClientId: '507312397854-3uo5vmoqovef5sbjd9fug0eterqh5poi.apps.googleusercontent.com',
    iosClientId: '507312397854-2dvq85obqi8etk5gi4hd9esu0ti1m2h6.apps.googleusercontent.com',
    iosBundleId: 'com.example.rmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD59W4KGWYnPbGP7w427HwhWmh0MTT41T0',
    appId: '1:507312397854:ios:0552116ffa5f1e7a0c580f',
    messagingSenderId: '507312397854',
    projectId: 'rec-mart',
    databaseURL: 'https://rec-mart-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rec-mart.appspot.com',
    androidClientId: '507312397854-3uo5vmoqovef5sbjd9fug0eterqh5poi.apps.googleusercontent.com',
    iosClientId: '507312397854-2dvq85obqi8etk5gi4hd9esu0ti1m2h6.apps.googleusercontent.com',
    iosBundleId: 'com.example.rmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlhAH1x2EmDT0RvK1Yql9Oq6XIzbzUkO8',
    appId: '1:507312397854:web:47b840da26e1751e0c580f',
    messagingSenderId: '507312397854',
    projectId: 'rec-mart',
    authDomain: 'rec-mart.firebaseapp.com',
    databaseURL: 'https://rec-mart-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rec-mart.appspot.com',
    measurementId: 'G-LWWSWDX7P7',
  );

}